### ISSUE TITLE
macos compile with wolfssl-5.6.2 display error

### ISSUE THREAD

**Issue by spacexnasa** [ngtcp2/ngtcp2#839]
macos intel 13.4

brew install wolfssl
when compile with ngtcp2

 90%] Built target ngtcp2_crypto_wolfssl
[ 91%] Building CXX object examples/CMakeFiles/wsslserver.dir/shared.cc.o
[ 92%] Building CXX object examples/CMakeFiles/wsslclient.dir/tls_client_session_wolfssl.cc.o
[ 93%] Building CXX object examples/CMakeFiles/wsslclient.dir/tls_session_base_wolfssl.cc.o
/home/ngtcp2/examples/tls_client_context_wolfssl.cc:63:7: error: use of undeclared identifier 'wolfSSL_SESSION_get_max_early_data'
  if (wolfSSL_SESSION_get_max_early_data(session) !=
      ^
[ 93%] Building CXX object examples/CMakeFiles/wsslclient.dir/util_wolfssl.cc.o
1 error generated.
make[2]: *** [examples/CMakeFiles/wsslclient.dir/build.make:146: examples/CMakeFiles/wsslclient.dir/tls_client_context_wolfssl.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 93%] Building CXX object examples/CMakeFiles/wsslserver.dir/tls_server_context_wolfssl.cc.o
[ 95%] Building CXX object examples/CMakeFiles/wsslserver.dir/tls_server_session_wolfssl.cc.o
[ 96%] Building CXX object examples/CMakeFiles/wsslserver.dir/tls_session_base_wolfssl.cc.o
[ 97%] Building CXX object examples/CMakeFiles/wsslserver.dir/util_wolfssl.cc.o
/home/ngtcp2/examples/tls_client_session_wolfssl.cc:126:19: error: use of undeclared identifier 'wolfSSL_SESSION_get_max_early_data'
                  wolfSSL_SESSION_get_max_early_data(session)) {
                  ^
/home/ngtcp2/examples/tls_client_session_wolfssl.cc:128:17: error: use of undeclared identifier 'wolfSSL_set_quic_early_data_enabled'
                wolfSSL_set_quic_early_data_enabled(ssl_, 1);
                ^
2 errors generated.
make[2]: *** [examples/CMakeFiles/wsslclient.dir/build.make:160: examples/CMakeFiles/wsslclient.dir/tls_client_session_wolfssl.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:411: examples/CMakeFiles/wsslclient.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 98%] Linking CXX executable wsslserver
[ 98%] Built target wsslserver
make: *** [Makefile:146: all] Error 2
