### ISSUE TITLE
Issues compiling with OpenSSL 3.5.1

### ISSUE THREAD

**Issue by qcybb** [ngtcp2/ngtcp2#1694]
Here are the issues I ran in to when trying to compile with OpenSSL 3.5.1 (now fully supports QUIC)

Any idea when support will be added?

```
--- vquic/libcurlu_la-curl_ngtcp2.lo ---
In file included from vquic/curl_ngtcp2.c:38:
/usr/local/include/ngtcp2/ngtcp2_crypto_quictls.h:73:3: error: unknown type name 'OSSL_ENCRYPTION_LEVEL'
   73 |   OSSL_ENCRYPTION_LEVEL ossl_level);
      |   ^
/usr/local/include/ngtcp2/ngtcp2_crypto_quictls.h:82:15: error: unknown type name 'OSSL_ENCRYPTION_LEVEL'
   82 | NGTCP2_EXTERN OSSL_ENCRYPTION_LEVEL
      |               ^
--- vquic/libcurlu_la-curl_quiche.lo ---

--- vquic/libcurlu_la-curl_ngtcp2.lo ---
vquic/curl_ngtcp2.c:2543:3: error: call to undeclared function 'SSL_set_quic_use_legacy_codepoint'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
 2543 |   SSL_set_quic_use_legacy_codepoint(ctx->tls.ossl.ssl, 0);
      |   ^
3 errors generated.
*** [vquic/libcurlu_la-curl_ngtcp2.lo] Error code 1
```

There could be more, but this is as far as I got before it stopped.

**Comment by tatsuhiro-t** [comment]
You are building curl, not ngtcp2.  Report to the curl project.
